### ISSUE TITLE
Case when ini has no section

### ISSUE THREAD

**Issue by sosie-js** [bartbes/inifile#1]
...then it crashes on parse() at line 88.
I suggest to introduce a virtual section "__top__"

**Comment by bartbes** [comment]
I've pushed a fix for the error to the develop branch (274bb1e0ce62a8743e83cfdfe1e313c292f91bdf).

I opted to treat it as a parse error, instead of trying to fix it up, as any section name could conflict with an existing section.

Can you confirm this fixes your issue?

**Comment by sosie-js** [comment]
Yes it fixes the issue but allows no more to read ini files that has no section at all which is my case with mpv config files where there is no chance to have conflict with a section name like in the example config - see the options.read_options mechanism from https://github.com/mpv-player/mpv/blob/master/DOCS/man/lua.rst
priority is given by get_opt --script-opts=env-optionA=valueA,env-optionB=valueB,...,env-optionX=valueX
then the config file env.conf
 `# comment
optionA=Hello World

optionB=9999

optionC=no
...
optionX=valueX `

and when no param and no config then failsafe
is given by lua table

 `local options = {

    optionA = "defaultvalueA",

    optionB = -0.5,

    optionC = true,

     optionX=valueX ,

} `

The gardian of the key is 
read_options(options, "env") that manages conflicts by priority.
if valueA is provided then otiionA is valueA
else optionA is Hello World
if we comment optionA in the config then optionA value is  "defaultvalueA"

**Comment by bartbes** [comment]
In this case, can’t you manually prefix the file with “[top]\n”?

**Comment by sosie-js** [comment]
it is an idea, don't bother I succeed to patch your code aside mine and hook it so it will use my patched version .
